baseURL = "https://andrewblance.github.io/"
languageCode = "en-us"
title = "Andrew's Webpage"
theme = "hugo-base16-theme"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Posts"
    url =  "/posts/"
    weight = "2"
  [[menu.nav]]
    name = "About"
    url = "/aboutme/"
    weight = "3"

