baseURL = "https://andrewblance.github.io/"
languageCode = "en-us"
title = "Andrew's Webpage"
theme = "hugo-base16-theme"

[params]
    aboutURL = "https://andrewblance.github.io/aboutme/" 
    aboutTitle = "About Me"
