baseURL = "https://andrewblance.github.io/"
languageCode = "en-us"
title = "Home"
theme = "hugo-base16-theme"

[params]
    aboutURL = "https://andrewblance.github.io/aboutme/" 
    aboutTitle = "About Me"
    postsURL = "https://andrewblance.github.io/posts/"
    postsTitle = "Posts"

